### PR TITLE
feat: Implementations of graphical tool to diff and merge files

### PR DESCRIPTION
**Pull request by boulevard-h**
Meld is a graphical diff viewer and merge application for the GNOME desktop. It supports 2 and 3-file diffs, recursive directory diffs, diffing of directories under version control (Bazaar, Codeville, CVS, Darcs, Fossil SCM, Git, Mercurial, Monotone, Subversion), as well as the ability to manually and automatically merge file differences.

Log: Implementations of graphical tool to diff and merge files

Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/242

### CODE REVIEW

**Comment by boulevard-h** [comment]
@chenchongbiao

**Comment by boulevard-h** [comment]
@Zeno-sole

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
